spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    password: system
     
    username: system
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
 
    show-sql: true 
server:
  port: 4040